name: Run Course Crawler

on:
  schedule:
    # 每天台灣時間早上 8 點執行 (UTC 00:00)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-crawler:
    name: Execute Course Crawler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync

      - name: Create .env file
        run: |
          echo "DB_URI=${{ secrets.DB_URI }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME || 'thu_course' }}" >> .env

      - name: Run crawler
        run: |
          uv run main.py

      - name: Upload logs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawler-logs-${{ github.run_number }}
          path: |
            *.log
            logs/
          retention-days: 7
